### ISSUE TITLE
Document the Experiment class

### ISSUE THREAD

**Issue by sotte** [GRAAL-Research/poutyne#14]
First of all, I like the library!

The Experiment class, which looks really interesting, is not part of the docs but it should be.

**Comment by freud14** [comment]
Hi,

Thank you for you comment.

Indeed, the Experiment class is really useful feature as it encapsulates a lot of feature that you want to use when training (or continue the training of) a neural network. However, the Experiment class is still an experimental feature of the library, and thus, its API could change between versions. Also, since it does a lot of things and has a lot of logic in it, I did not take the time yet to document it. If you want to document it as an experimental feature of the library, go ahead and make me a PR. The documentation page should have a big warning about the experimental side of the feature.

**Comment by sotte** [comment]
Hey,

I basically had have my own little experiment class that wraps some PyToune functionality not unlike yours. I just stumbled upon the class when I was reading the source. I'll run some experiments with PyToune's Experiment class on the weekend and give you feedback.

**Comment by freud14** [comment]
Btw, look at the dev branch of PyToune where I fixed some bugs and added a few minor features on the Experiment class.

**Comment by freud14** [comment]
Finally, I just released a new minor version of PyToune that contains the latest modifications to the Experiment class.

**Comment by sotte** [comment]
I'll give it a test run, thanks!

**Comment by freud14** [comment]
Fixed in #48.
